services:
  postgres:
    image: postgres:16-alpine
    container_name: app_db
    environment:
      POSTGRES_USER: scrumno
      POSTGRES_PASSWORD: 3003
      POSTGRES_DB: app
    ports:
      # 5433 чтобы не конфликтовать с локальным PostgreSQL на хосте
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scrumno -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: